package shopbase

//AutoGenerated ...
type AutoGenerated struct {
	Products []Products `json:"products"`
	Total    int        `json:"total"`
}

//Options ...
type Options struct {
	ID       int    `json:"id"`
	Value    string `json:"value"`
	Position int    `json:"position"`
}

//OptionSets ...
type OptionSets struct {
	ID       int       `json:"id"`
	Value    string    `json:"value"`
	Position int       `json:"position"`
	Options  []Options `json:"options"`
}

//Variants ...
type Variants struct {
	ID                 int64   `json:"id"`
	Title              string  `json:"title"`
	InventoryQuantity  int     `json:"inventory_quantity"`
	InventoryPolicy    string  `json:"inventory_policy"`
	Price              float64 `json:"price"`
	CompareAtPrice     float64 `json:"compare_at_price"`
	WeightUnit         string  `json:"weight_unit"`
	FulfillmentService string  `json:"fulfillment_service"`
	RequiresShipping   bool    `json:"requires_shipping"`
	Option1            int     `json:"option1"`
	Option2            int     `json:"option2"`
	Position           int     `json:"position,omitempty"`
}

//Images ...
type Images struct {
	ID       int    `json:"id"`
	Src      string `json:"src"`
	Width    int    `json:"width"`
	Height   int    `json:"height"`
	Position int    `json:"position"`
}

//Products ...
type Products struct {
	ID            int64        `json:"id"`
	Handle        string       `json:"handle"`
	Title         string       `json:"title"`
	BodyHTML      string       `json:"body_html"`
	PublishedAt   int          `json:"published_at"`
	Published     bool         `json:"published"`
	Available     bool         `json:"available"`
	CreatedAt     int          `json:"created_at"`
	UpdatedAt     int          `json:"updated_at"`
	OptionSets    []OptionSets `json:"option_sets"`
	Variants      []Variants   `json:"variants"`
	Images        []Images     `json:"images"`
	CustomOptions interface{}  `json:"custom_options"`
	Price         float64      `json:"price"`
}
